version: "3"
services:
  hub:
    image: selenium/hub:4.22.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300

  chrome:
    image: selenium/node-chrome:4.22.0
#    container_name: chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_MAX_INSTANCES=2
    ports:
      - "5900:5900"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1g"

  firefox:
    image: selenium/node-firefox:4.22.0
    container_name: firefox
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_MAX_INSTANCES=4
    ports:
      - "5901:5900"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1g"
